name: Dispatch Update Submodule
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update to ssm-client Project
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: oblitorum/parent
          event-type: update-submodule
          client-payload: |-
            {
              "repo": "${{ github.event.repository.name }}",
              "commit_message": ${{ toJson(github.event.head_commit.message) }}
            }
